[archimedlight-release-fixtures]
git-tree-sha1 = "416d3f0ff67e5f477f88990dab6cf5b7170cea40"
lazy = true

    [[archimedlight-release-fixtures.download]]
    url = "https://github.com/ARCHIMED-platform/ArchimedLight.jl/releases/download/v0.0.1/archimedlight-release-fixtures-v0.0.1.tar.gz"
    sha256 = "c16169a5e5a2cdfa0b6fb675981e9b0fdbe9ecd5028f8fab0f0d5f59f08c503d"
