name = "ArchimedLight"
uuid = "ca362a0f-208d-4994-8e0e-d922fd0d438a"
authors = ["Rémi Vezy <VEZY@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[deps]
Meshes = "eacbb407-ea5a-433e-ab97-5258b1ca43fa"
MultiScaleTreeGraph = "dd4a991b-8a45-4075-bede-262ee62d5583"
PlantGeom = "5edaa67e-25db-4eb9-bf81-05d793b2238d"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Unitful = "1986cc42-f94f-5a68-af5c-568840ba703d"

[compat]
Meshes = "0.54.6"
MultiScaleTreeGraph = "0.14.4"
PlantGeom = "0.14.0"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
