name = "ArchimedLight"
uuid = "ca362a0f-208d-4994-8e0e-d922fd0d438a"
authors = ["Rémi Vezy <VEZY@users.noreply.github.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
